### ISSUE TITLE
请问如何实现侧栏的滚动条随着高度改变`滚动条适应改变

### ISSUE THREAD

**Issue by yudan215** [PanJiaChen/vue-element-admin#1039]
http://element-cn.eleme.io/#/zh-CN/component/installation 官方文档的侧栏也是用了el-scrollbar,但是我尝试改变页面的高度,官方的文档滚动条就会错位

但是vue-element-admin的侧栏我测试了一些改变高度后`滚动条也会跟着改变,请问是如何实现的?

**Comment by PanJiaChen** [comment]
```css
.el-scrollbar__view {
        height: 100%;
      }
```
