### ISSUE TITLE
请问一下  首页那个hamburger的svg如何换颜色

### ISSUE THREAD

**Issue by lxk0301** [PanJiaChen/vue-element-admin#1265]
![image](https://user-images.githubusercontent.com/21308593/47554906-10081e00-d93d-11e8-8e24-70390567ed08.png)

**Comment by PanJiaChen** [comment]
```css
.hamburger{
	fill: red;
}
```
