### ISSUE TITLE
复合型输入框显示bug

### ISSUE THREAD

**Issue by MrSong0607** [PanJiaChen/vue-element-admin#2449]
## Bug report（问题描述）
element的复合型输入框，在table 表头上的显示bug
#### Steps to reproduce（问题复现步骤）
custom-theme的样式导致element-ui的复合型输入框显示出问题
```css
.el-table th div {
    display: inline-block;
    padding-left: 10px;
    padding-right: 10px;
    line-height: 40px;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```
```html
    <el-table>
      <el-table-column align="right">
        <template v-slot:header="{row}">
          <el-input placeholder="请输入内容" class="input-with-select">
            <el-button slot="append" icon="el-icon-search" />
          </el-input>
        </template>
      </el-table-column>
    </el-table>
```
#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/13636643/62534734-5c916a00-b87c-11e9-8074-6430587253ca.png)

#### Other relevant information（格外信息）
- Your OS:windows 10
- Node.js version:v12.7.0.
- vue-element-admin version:4.2.1
