### ISSUE TITLE
穿梭框出现布局的bug

### ISSUE THREAD

**Issue by xuzining** [PanJiaChen/vue-element-admin#2844]
在框架中使用穿梭框，第一行数据和第二行数据中间会空一行数据的距离

**Comment by mayunhai** [comment]
没问题啊，是不是自己的样式表里存在和 element UI的样式冲突

**Comment by luliangce** [comment]
实测通过覆盖样式可以解决, 成因并没有深究. 暂时也没有发现负面影响. 
```CSS
.el-transfer-panel__item.el-checkbox {
  display: block;
}
```
