### ISSUE TITLE
el-table 第一列固定，且对单元格设置多行省略css后Safari浏览器上表格行高出现错乱

### ISSUE THREAD

**Issue by Anyhow-Lee** [PanJiaChen/vue-element-admin#4152]
## Bug report（问题描述）
需要每个单元格展示超出三行省略

#### Steps to reproduce（问题复现步骤）
以 vue-element-admin 官方代码为例
1. 设置第一列fixed，且每一列均设置width(无 min-width)
2. 在 `src/styles/index.scss` 中写css
```css
.el-table .cell{
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  word-break: break-all;
  line-height: 23px;
}
```
此时效果为：
- 左侧固定列错位
- 固定列只展示14个数据
![image](https://user-images.githubusercontent.com/54074451/233818988-ce5dd52c-0b66-4556-9203-1fadeb7b2260.png)
![image](https://user-images.githubusercontent.com/54074451/233821901-5e847134-b0fa-4725-ab8d-f1048f5e610c.png)

3. 在网上看见有说增加 max-height 任然无法完全解决
```css
.el-table .cell{
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  word-break: break-all;
  line-height: 23px;
  max-height: 69px;
}
````
此时效果：
![image](https://user-images.githubusercontent.com/54074451/233822449-c19664c4-f510-4f9f-a52d-c0740eba1ac7.png)

![image](https://user-images.githubusercontent.com/54074451/233822434-880e4589-4356-4887-bc05-514d9550aa1f.png)
