### ISSUE TITLE
升级webpack4之后，element-ui 的button在自定义样式后打完包部署样式不能生效

### ISSUE THREAD

**Issue by Mr-arvin** [PanJiaChen/vue-element-admin#923]
发现一个问题，在此项目升级完webpack4.0之后，打包出来的文件css样式上和之前打包出来的略有不同，如element-ui的这个button样式：
```css
.el-button--primary {
  background-color: #4994c5;
  border-color: #4994c5;
  &:hover,&:focus {
    background-color: #529dce;
    border-color: #529dce;
  }
}
```
在升级之前打包出来的按钮是生效的，但是在升级完之后，按钮的样式就恢复成element-ui原生button的颜色了。我找了很久也没有找到问题出在哪里，救助开源者潘神！
